# Generated by Django 5.2.1 on 2025-05-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_coursematerial_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
